### PR TITLE
Feature/browser extensions

### PR DESCRIPTION
**Pull request by Yuyz0112**
Browser extensions' code were created based on this boilerplate: https://github.com/EmailThis/extension-boilerplate

I keep the `README.md` from the boilerplate into the browser extensions folder so developers can get familiar with the whole structure quickly.

Also I have already publish chrome and firefox extensions in my account, but feel free to publish in a more official account so we can maintain it better.

### CODE REVIEW

**Comment by rp4rk** [comment]
Can you elaborate and give some screenshots please? I've installed this addon on my browser and it has seemingly done nothing.

**Comment by Yuyz0112** [comment]
@rp4rk Just add a how to use doc with screenshots. Please let me know if there is still any problem or things need to be explained better.

**Comment by MartijnHols** [comment]
Sorry for taking so long - reviewing this was non obvious. Thanks for this, I'm going to merge it, but I do have some suggestions;

- Nit: it's a *browser-extension* (singular)
- Different license making it less obvious to work on, but I'll concede that the project's current license probably isn't optimal either but I don't really want to change terms or use more words
- Introduces a new builder with gulp
- The icon in the toolbar could be grayed out when something can't be analyzed and get colorized when it can be analyzed, giving a much easier visual feedback. React Developer Tools works this way iirc. I think it would be nice if this went one step further in removing the popover modal and instead just straight up analyzing when clicking the icon. This also solves my next point;
- The emphasis on report code feels wrong. Users can enter report urls or whatever too and in the end it's not really useful information to them if they can already click a link to import.
- I think the best case would be if a link to the analyzer is shown directly in the WCL page. I'm not sure it's possible, but it probably is with extensions like AdBlock manipulating site content. I reckon showing an analyzer icon next to players in WCL rankings, summary, healers and a large button in a specific healer view would be nice (only for supported specs ofc). This would probably take quite a bit of time to build though.

**Comment by Yuyz0112** [comment]
Thanks for the comprehensive suggestions, this PR is a very beginning version of our browser extension and I will keep improve it.

I have understood most of the suggestions and will do it later, maybe this weekend if I am free.
But there is several questions I want to verify:

- What is the purpose of using gulp? Currently we are not depending on it.
- Is the license of this browser extension boilerplate conflict with WoW Analyzer's license or credit? Not quite familiar with licenses and not sure how to avoid such a conflict.

**Comment by MartijnHols** [comment]
It looks to be the build system, strange that you haven't used it. https://github.com/Yuyz0112/WoWAnalyzer/blob/36b4e9d0e66792b001eaee3544bf403a074268b3/browser-extensions/gulpfile.babel.js

I didn't look at any conflicts with the license as it shouldn't matter, it's mostly that figuring out licenses takes time and thus slows down development. Adding a new license add to that wasted time.

**Pull request merged**
