### PR TITLE
[WIP] RDruid legendary shoulders

### PR DESCRIPTION
**Pull request by rubensayshi**
Work in progress
----------------------
Don't merge yet

### CODE REVIEW

**Comment by rubensayshi** [comment]
idk, maybe it would be a good idea to extract some of the generic rejuv tracking stuff from ToL and Tearstone into a base module that the others make use of?

**Comment by rubensayshi** [comment]
also; @MartijnHols you think there's any way we could do a very basic test setup to feed some events into a `CombatParser`?

**Comment by rubensayshi** [comment]
@buimichael the question with shoulders is, should we simply do bonusticks * avgtickhealing like I'm doing atm, or would you want to account for the bonus ticks also overhealing ...

the thing is, this kinda applies to almost everything, if you increase healing of something it also results in more overhealing... it's just that due to the nature of shoulders it seems like it's more than usual.

**Comment by rubensayshi** [comment]
hmm I just realized that I'm counting the amount of times the shoulders extend rejuv and then multiple that by the healing amount of 1 tick, but the 3s extension that shoulders give is more than a single tick, depending on haste...

**Comment by MartijnHols** [comment]
You should be able to trigger events from a test through the public methods like triggerEvent or parseEvents, as desired.

**Comment by buimichael** [comment]
@rubensayshi I think using bonusticks * avgtickhealing is fine. Yes, this is an estimation, but doing this way we won't disregard hidden/complex stuff like 4PT20, flourish, EoG, deep rooted etc which the shoulders positively contributes to.

I also think we should somehow bake in cultivation + dreamwalker into the equation, since they are a side-effect of rejuvenation. (This is entirely true for tearstone especially)

I'm open for suggestions/discussion though on what you think would be more accurate.

**Comment by rubensayshi** [comment]
the thing is that my current code counts the bonus **extensions**, it won't be aware of how many bonus ticks that will actually be (because due to haste each 3s extension will be 1.xx ticks).

tbh I want to see if I can code it up to properly count durations of rejuvs, if I can accurately calculate for each rejuv how long the duration is (if it matches the `removebuff` timestamps) then we could much better attribute things, but that's a lot of work ...

I think rdruid in general atm is very hard to analyze because there's so many things that enhance eachother, like t19 4pc gives more rejuvs, meaning more shoulders procs, meaning more t19 procs, etc..  
it's kinda impossible to really isolate the usefulness of either of them when you have a parse with both ...

**Comment by buimichael** [comment]
>tbh I want to see if I can code it up to properly count durations of rejuvs,
Having that would make lots of thing a lot more accurate and easier to implement. Such as checking premature HoT applications, issue #76.

>it's kinda impossible to really isolate the usefulness of either of them when you have a parse with both
Yes I agree, that's why an estimation/average of the total effect from rejuvenation is imo the most accurate since we're taking all the complex variables into account. Entirely disregarding it would be less accurate imo.

**Comment by MartijnHols** [comment]
Is this still WIP or can it be merged? Please in the future only make a pull request when you're ready to

**Comment by MartijnHols** [comment]
Please make a new PR when you're ready to merge.

**Pull request closed without merging**
